POST http://127.0.0.1:10000/api/v1/message/chats/0195d2cf-4f0a-7cdb-b36e-3c500f02d4b4/messages
Content-Type: application/json
Authorization: Bearer <login-token>

{
    "text": "Hello from message service",
    "attachments": [
        "f353ca91-4fc5-49f2-9b9e-304f83d11914.png"
    ]
}
