POST http://127.0.0.1:10000/api/v1/message/chats
Content-Type: application/json
Authorization: Bearer <login-token>

{
    "memberUuids": [
        "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"
    ],
    "name": "Private chat",
    "avatar": "https://cdn.example.com/chat-avatar.png",
    "isPrivate": true
}
