server {
    listen 80;
    server_name _;

    location / {
        proxy_pass http://vox-ui-static-app:5174/;
        proxy_http_version 1.1;
        include /etc/nginx/includes/vox-proxy-headers.conf;
    }

    include /etc/nginx/includes/vox-api-locations.conf;
}

server {
    listen 81;
    server_name _;

    location / {
        proxy_pass http://vox-ui-app:5173/;
        proxy_http_version 1.1;
        include /etc/nginx/includes/vox-proxy-headers.conf;
    }

    include /etc/nginx/includes/vox-api-locations.conf;
}
