services:
  ui:
    container_name: vox-ui-app
    build:
      context: ..
      dockerfile: docker/app.Dockerfile
      target: dev
    env_file:
      - .env.development
    volumes:
      - ..:/app
      - vox-ui-node-modules:/app/internal/node_modules
    working_dir: /app/internal
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
    networks:
      - vox-shared-network

  ui-static:
    container_name: vox-ui-static-app
    build:
      context: ..
      dockerfile: docker/app.Dockerfile
      target: prod
    env_file:
      - .env.development
    environment:
      UI_PORT: "5174"
    command: ["/usr/local/bin/ui-service"]
    networks:
      - vox-shared-network

volumes:
  vox-ui-node-modules:
    name: vox-ui-node-modules

networks:
  vox-shared-network:
    external: true
