services:
  auth:
    container_name: vox-auth-app
    build:
      context: ..
      dockerfile: docker/app.Dockerfile
    env_file:
      - .env.development
    networks:
      - vox-shared-network
      - vox-auth-local-network
    depends_on:
      - postgres

  postgres:
    container_name: ${POSTGRES_HOST}
    image: postgres:17
    env_file:
      - .env.development
    ports:
      - "10001:${POSTGRES_PORT}"
    volumes:
      - vox-auth-postgres-data:/var/lib/postgresql/data
    networks:
      - vox-auth-local-network

volumes:
  vox-auth-postgres-data:
    name: vox-auth-postgres-data

networks:
  vox-shared-network:
    external: true
  vox-auth-local-network:
    external: true
    name: vox-auth-local-network
