services:
  profile:
    container_name: vox-profile-app
    build:
      context: ..
      dockerfile: docker/app.Dockerfile
    env_file:
      - .env.development
    networks:
      - vox-shared-network
      - vox-profile-local-network
    depends_on:
      - postgres

  postgres:
    container_name: ${POSTGRES_HOST}
    image: postgres:17
    env_file:
      - .env.development
    ports:
      - "10003:${POSTGRES_PORT}"
    volumes:
      - vox-profile-postgres-data:/var/lib/postgresql/data
    networks:
      - vox-profile-local-network

volumes:
  vox-profile-postgres-data:
    name: vox-profile-postgres-data

networks:
  vox-shared-network:
    external: true
  vox-profile-local-network:
    external: true
    name: vox-profile-local-network
